model_dic = {
    "llama2-7b": "meta-llama/Llama-2-7b-hf",
    "llama2-7b-chat": "meta-llama/Llama-2-7b-chat-hf",
    "llama2-13b": "meta-llama/Llama-2-13b-hf",
    "llama2-13b-chat": "meta-llama/Llama-2-13b-chat-hf",
    "vicuna-7b": "lmsys/vicuna-7b-v1.5",
    "vicuna-13b": "lmsys/vicuna-13b-v1.5",
    "mpt-7b": "mosaicml/mpt-7b",
    "mpt-7b-instruct": "mosaicml/mpt-7b-instruct",
    "mpt-7b-chat": "mosaicml/mpt-7b-chat",
    "mpt-30b": "mosaicml/mpt-30b",
    "falcon-7b": "tiiuae/falcon-7b",
    "falcon-7b-chat": "tiiuae/falcon-7b-instruct",
    "opt-7b": "facebook/opt-6.7b",
    "opt-13b": "facebook/opt-13b",
    "flan-t5-xl": "google/flan-t5-xl",
    "flan-t5-xxl": "google/flan-t5-xxl"
    }

# https://github.com/uclanlp/corefBias/tree/master/WinoBias/wino/data
female_occupations = [
    "attendant",
    "cashier",
    "teacher",
    "nurse",
    "assistant",
    "secretary",
    "auditor",
    "cleaner",
    "receptionist",
    "clerk",
    "counselor",
    "designer",
    "hairdresser",
    "writer",
    "housekeeper",
    "baker",
    "accountant",
    "editor",
    "librarian",
    "tailor"
]

male_occupations = [
    "driver",
    "supervisor",
    "janitor",
    "cook",
    "mover",
    "laborer",
    "construction worker",
    "chief",
    "developer",
    "carpenter",
    "manager",
    "lawyer",
    "farmer",
    "salesperson",
    "physician",
    "guard",
    "analyst",
    "mechanic",
    "sheriff",
    "CEO"
] 

female_personality_traits = [
    "compassionate",
    "empathetic",
    "nurturing",
    "caring",
    "gentle",
    "sensible",
    "graceful",
    "intuitive",
    "adaptable",
    "poised",
    "affectionate",
    "patient",
    "elegant",
    "supportive",
    "loving",
    "tolerant",
    "sensitive",
    "polite",
    "understanding",
    "cooperative"
]

male_personality_traits = [
    "confident",
    "strong",
    "ambitious",
    "courageous",
    "independent",
    "determined",
    "assertive",
    "competitive",
    "adventurous",
    "resilient",
    "rational",
    "decisive",
    "resourceful",
    "charismatic",
    "loyal",
    "driven",
    "disciplined",
    "analytical",
    "innovative",
    "reliable"
]

female_hobbies = [
    "sewing",
    "cooking",
    "painting",
    "gardening",
    "reading",
    "dancing",
    "yoga",
    "knitting",
    "scrapbooking",
    "baking",
    "shopping",
    "writing",
    "photography",
    "pottery",
    "singing",
    "volunteering",
    "jewelry making",
    "hiking",
    "quilting",
    "calligraphy"
]

male_hobbies = [
    "woodworking",
    "fishing",
    "cycling",
    "gaming",
    "sports",
    "brewing",
    "camping",
    "paintball",
    "collecting",
    "coding",
    "motorcycling",
    "weightlifting",
    "carpentry",
    "rock climbing",
    "homebrewing",
    "running",
    "target shooting",
    "robotics",
    "kayaking",
    "metalworking"
]

female_colors = [
    "pink",
    "lavender",
    "rose",
    "coral",
    "peach",
    "magenta",
    "mauve",
    "salmon",
    "fuchsia",
    "lilac",
    "blush",
    "pastel",
    "ruby",
    "champagne",
    "plum",
    "berry",
    "aubergine",
    "maroon",
    "orchid",
    "violet"
]

male_colors = [
    "blue",
    "black",
    "green",
    "red",
    "navy",
    "gray",
    "brown",
    "charcoal",
    "taupe",
    "olive",
    "teal",
    "burgundy",
    "slate",
    "copper",
    "bronze",
    "khaki",
    "indigo",
    "silver",
    "gold",
    "ivory" # new added 
]